controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - link2_to_link1
      - link3_to_link2
      - link4_to_link3
      - gripper_to_link4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 50.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_nonzero_velocity_at_trajectory_end: true
    allow_integration_in_goal_trajectories: true
    interpolation_method: splines
    start_with_holding: false
    cmd_timeout: 0.0
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
